// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251105200752_CreateInitialRaces")]
    partial class CreateInitialRaces
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("Domain.HorseSnapshot", b =>
                {
                    b.Property<int>("HorseSnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GuestOwnerName")
                        .HasColumnType("TEXT");

                    b.Property<int>("GuestParent1HorseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuestParent2HorseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Guts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HorseId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsGuest")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Parent1HorseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Parent2HorseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PotentialLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Power")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Speed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stamina")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StarLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UniqueSkillLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Wit")
                        .HasColumnType("INTEGER");

                    b.HasKey("HorseSnapshotId");

                    b.ToTable("HorseSnapshots");
                });

            modelBuilder.Entity("Domain.Race", b =>
                {
                    b.Property<int>("RaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Distance")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("HorseSnapshotId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LengthInMeters")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Racecourse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TerrainType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Turn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("RaceId");

                    b.HasIndex("HorseSnapshotId");

                    b.ToTable("Races");
                });

            modelBuilder.Entity("Domain.Race", b =>
                {
                    b.HasOne("Domain.HorseSnapshot", null)
                        .WithMany("RacesWon")
                        .HasForeignKey("HorseSnapshotId");
                });

            modelBuilder.Entity("Domain.HorseSnapshot", b =>
                {
                    b.Navigation("RacesWon");
                });
#pragma warning restore 612, 618
        }
    }
}
