// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("Domain.HorseSnapshot", b =>
                {
                    b.Property<int>("HorseSnapshotId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HorseId")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Parent1HorseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Parent2HorseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<int>("StarLevel")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PotentialLevel")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<int>("UniqueSkillLevel")
                        .IsRequired()
                        .HasColumnType("INTEGER");
                    
                    b.Property<int>("Speed")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stamina")
                        .IsRequired()
                        .HasColumnType("INTEGER");
                    
                    b.Property<int>("Power")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Guts")
                        .IsRequired()
                        .HasColumnType("INTEGER");
                    
                    b.Property<int>("Wit")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsGuest")
                        .IsRequired()
                        .HasColumnType("INTEGER"); //Bit for SQL or Integer for Sqlite

                    b.Property<string>("GuestOwnerName")
                        .HasColumnType("TEXT");

                    b.Property<int>("GuestParent1HorseId")
                        .HasColumnType("INTEGER");
                    
                    b.Property<int>("GuestParent2HorseId")
                        .HasColumnType("INTEGER");
                    
                    b.HasKey("HorseSnapshotId");

                    b.ToTable("HorseSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
